// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hvmwkwxznqegtehsilea.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh2bXdrd3h6bnFlZ3RlaHNpbGVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5MTI4MTUsImV4cCI6MjA3MjQ4ODgxNX0.Wk1U2qcWVhKbFod9lgIROLu7zzqI4BI9Wdakls94YtU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});